# fly.toml file generated for turbovpb-server on 2022-08-30T08:25:25+02:00

app = "turbovpb-server"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  RUST_LOG = "turbovpb_server=debug"
  RUST_BACKTRACE = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 5000
    soft_limit = 4000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Check the website being served
  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"

  # Check the API
  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/api/status"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"
