[package]
name = "turbovpb-server"
authors = ["Evan Schwartz <evan@turbovpb.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.8", features = ["ws"] }
dashmap = "6"
futures = "0.3"
prometheus = { version = "0.14", default-features = false }
serde = { version = "1.0", features = ["derive"] }
tinytemplate = "1.2"
tokio-rusqlite = { version = "0.7", features = ["bundled"] }
tokio = { version = "1.20", default-features = false, features = [
    "macros",
    "net",
    "parking_lot",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tower-http = { version = "0.6", features = ["compression-full", "fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = true
codegen-units = 1
