# fly.toml file generated for turbovpb-server on 2022-08-30T08:25:25+02:00

app = "turbovpb-server"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  RUST_LOG = "turbovpb_server=debug"
  RUST_BACKTRACE = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
port = 8081
path = "/metrics"

[http_service]
  internal_port = 8080
  force_https = true
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/status"
